
services:
  - type: web
    name: flask-finance-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    env: python
    plan: free
    region: frankfurt  #.
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.10